name: ETL pipeline
on:
  push:
    branches:
    - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Chexkout job1 code
        uses: actions/checkout@v7
      - name: Run job1 code
        run: python job1.py
    job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Chexkout job2 code
        uses: actions/checkout@v7
      - name: Run job2 code
        run: python job2.py
    job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Chexkout job3 code
        uses: actions/checkout@v7
      - name: Run job3 code
        run: python job3.py
    job4:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Chexkout job4 code
        uses: actions/checkout@v7
      - name: Run job4 code
        run: python job4.py
    job5:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - name: Chexkout job5 code
        uses: actions/checkout@v7
      - name: Run job5 code
        run: python job5.py
    job6:
    needs: [job4,job5]
    runs-on: ubuntu-latest
    steps:
      - name: Chexkout job6 code
        uses: actions/checkout@v7
      - name: Run job6 code
        run: python job6.py